// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.zomtec.em2012.domain;

import eu.zomtec.em2012.domain.Bet;
import eu.zomtec.em2012.domain.BetDataOnDemand;
import eu.zomtec.em2012.domain.BetIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BetIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BetIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BetIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BetIntegrationTest: @Transactional;
    
    @Autowired
    private BetDataOnDemand BetIntegrationTest.dod;
    
    @Test
    public void BetIntegrationTest.testCountBets() {
        Assert.assertNotNull("Data on demand for 'Bet' failed to initialize correctly", dod.getRandomBet());
        long count = Bet.countBets();
        Assert.assertTrue("Counter for 'Bet' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BetIntegrationTest.testFindBet() {
        Bet obj = dod.getRandomBet();
        Assert.assertNotNull("Data on demand for 'Bet' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Bet' failed to provide an identifier", id);
        obj = Bet.findBet(id);
        Assert.assertNotNull("Find method for 'Bet' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Bet' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BetIntegrationTest.testFindAllBets() {
        Assert.assertNotNull("Data on demand for 'Bet' failed to initialize correctly", dod.getRandomBet());
        long count = Bet.countBets();
        Assert.assertTrue("Too expensive to perform a find all test for 'Bet', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Bet> result = Bet.findAllBets();
        Assert.assertNotNull("Find all method for 'Bet' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Bet' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BetIntegrationTest.testFindBetEntries() {
        Assert.assertNotNull("Data on demand for 'Bet' failed to initialize correctly", dod.getRandomBet());
        long count = Bet.countBets();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Bet> result = Bet.findBetEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Bet' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Bet' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BetIntegrationTest.testFlush() {
        Bet obj = dod.getRandomBet();
        Assert.assertNotNull("Data on demand for 'Bet' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Bet' failed to provide an identifier", id);
        obj = Bet.findBet(id);
        Assert.assertNotNull("Find method for 'Bet' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBet(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Bet' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BetIntegrationTest.testMergeUpdate() {
        Bet obj = dod.getRandomBet();
        Assert.assertNotNull("Data on demand for 'Bet' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Bet' failed to provide an identifier", id);
        obj = Bet.findBet(id);
        boolean modified =  dod.modifyBet(obj);
        Integer currentVersion = obj.getVersion();
        Bet merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Bet' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BetIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Bet' failed to initialize correctly", dod.getRandomBet());
        Bet obj = dod.getNewTransientBet(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Bet' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Bet' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Bet' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BetIntegrationTest.testRemove() {
        Bet obj = dod.getRandomBet();
        Assert.assertNotNull("Data on demand for 'Bet' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Bet' failed to provide an identifier", id);
        obj = Bet.findBet(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Bet' with identifier '" + id + "'", Bet.findBet(id));
    }
    
}
