// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.zomtec.em2012.domain;

import eu.zomtec.em2012.domain.BetUserRole;
import eu.zomtec.em2012.domain.BetUserRoleDataOnDemand;
import eu.zomtec.em2012.domain.BetUserRoleIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BetUserRoleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BetUserRoleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BetUserRoleIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BetUserRoleIntegrationTest: @Transactional;
    
    @Autowired
    private BetUserRoleDataOnDemand BetUserRoleIntegrationTest.dod;
    
    @Test
    public void BetUserRoleIntegrationTest.testCountBetUserRoles() {
        Assert.assertNotNull("Data on demand for 'BetUserRole' failed to initialize correctly", dod.getRandomBetUserRole());
        long count = BetUserRole.countBetUserRoles();
        Assert.assertTrue("Counter for 'BetUserRole' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BetUserRoleIntegrationTest.testFindBetUserRole() {
        BetUserRole obj = dod.getRandomBetUserRole();
        Assert.assertNotNull("Data on demand for 'BetUserRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BetUserRole' failed to provide an identifier", id);
        obj = BetUserRole.findBetUserRole(id);
        Assert.assertNotNull("Find method for 'BetUserRole' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'BetUserRole' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BetUserRoleIntegrationTest.testFindAllBetUserRoles() {
        Assert.assertNotNull("Data on demand for 'BetUserRole' failed to initialize correctly", dod.getRandomBetUserRole());
        long count = BetUserRole.countBetUserRoles();
        Assert.assertTrue("Too expensive to perform a find all test for 'BetUserRole', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<BetUserRole> result = BetUserRole.findAllBetUserRoles();
        Assert.assertNotNull("Find all method for 'BetUserRole' illegally returned null", result);
        Assert.assertTrue("Find all method for 'BetUserRole' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BetUserRoleIntegrationTest.testFindBetUserRoleEntries() {
        Assert.assertNotNull("Data on demand for 'BetUserRole' failed to initialize correctly", dod.getRandomBetUserRole());
        long count = BetUserRole.countBetUserRoles();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<BetUserRole> result = BetUserRole.findBetUserRoleEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'BetUserRole' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'BetUserRole' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BetUserRoleIntegrationTest.testFlush() {
        BetUserRole obj = dod.getRandomBetUserRole();
        Assert.assertNotNull("Data on demand for 'BetUserRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BetUserRole' failed to provide an identifier", id);
        obj = BetUserRole.findBetUserRole(id);
        Assert.assertNotNull("Find method for 'BetUserRole' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBetUserRole(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'BetUserRole' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BetUserRoleIntegrationTest.testMergeUpdate() {
        BetUserRole obj = dod.getRandomBetUserRole();
        Assert.assertNotNull("Data on demand for 'BetUserRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BetUserRole' failed to provide an identifier", id);
        obj = BetUserRole.findBetUserRole(id);
        boolean modified =  dod.modifyBetUserRole(obj);
        Integer currentVersion = obj.getVersion();
        BetUserRole merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'BetUserRole' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BetUserRoleIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'BetUserRole' failed to initialize correctly", dod.getRandomBetUserRole());
        BetUserRole obj = dod.getNewTransientBetUserRole(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'BetUserRole' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'BetUserRole' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'BetUserRole' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BetUserRoleIntegrationTest.testRemove() {
        BetUserRole obj = dod.getRandomBetUserRole();
        Assert.assertNotNull("Data on demand for 'BetUserRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BetUserRole' failed to provide an identifier", id);
        obj = BetUserRole.findBetUserRole(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'BetUserRole' with identifier '" + id + "'", BetUserRole.findBetUserRole(id));
    }
    
}
