// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.zomtec.em2012.domain;

import eu.zomtec.em2012.domain.BetUserRole;
import eu.zomtec.em2012.domain.BetUserRoleDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect BetUserRoleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: BetUserRoleDataOnDemand: @Component;
    
    private Random BetUserRoleDataOnDemand.rnd = new SecureRandom();
    
    private List<BetUserRole> BetUserRoleDataOnDemand.data;
    
    public BetUserRole BetUserRoleDataOnDemand.getNewTransientBetUserRole(int index) {
        BetUserRole obj = new BetUserRole();
        setName(obj, index);
        return obj;
    }
    
    public void BetUserRoleDataOnDemand.setName(BetUserRole obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public BetUserRole BetUserRoleDataOnDemand.getSpecificBetUserRole(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        BetUserRole obj = data.get(index);
        Long id = obj.getId();
        return BetUserRole.findBetUserRole(id);
    }
    
    public BetUserRole BetUserRoleDataOnDemand.getRandomBetUserRole() {
        init();
        BetUserRole obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return BetUserRole.findBetUserRole(id);
    }
    
    public boolean BetUserRoleDataOnDemand.modifyBetUserRole(BetUserRole obj) {
        return false;
    }
    
    public void BetUserRoleDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = BetUserRole.findBetUserRoleEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'BetUserRole' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<BetUserRole>();
        for (int i = 0; i < 10; i++) {
            BetUserRole obj = getNewTransientBetUserRole(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
