// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.zomtec.em2012.domain;

import eu.zomtec.em2012.domain.BetUser;
import eu.zomtec.em2012.domain.BetUserDataOnDemand;
import eu.zomtec.em2012.domain.BetUserIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BetUserIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BetUserIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BetUserIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: BetUserIntegrationTest: @Transactional;
    
    @Autowired
    private BetUserDataOnDemand BetUserIntegrationTest.dod;
    
    @Test
    public void BetUserIntegrationTest.testCountBetUsers() {
        Assert.assertNotNull("Data on demand for 'BetUser' failed to initialize correctly", dod.getRandomBetUser());
        long count = BetUser.countBetUsers();
        Assert.assertTrue("Counter for 'BetUser' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BetUserIntegrationTest.testFindBetUser() {
        BetUser obj = dod.getRandomBetUser();
        Assert.assertNotNull("Data on demand for 'BetUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BetUser' failed to provide an identifier", id);
        obj = BetUser.findBetUser(id);
        Assert.assertNotNull("Find method for 'BetUser' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'BetUser' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BetUserIntegrationTest.testFindAllBetUsers() {
        Assert.assertNotNull("Data on demand for 'BetUser' failed to initialize correctly", dod.getRandomBetUser());
        long count = BetUser.countBetUsers();
        Assert.assertTrue("Too expensive to perform a find all test for 'BetUser', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<BetUser> result = BetUser.findAllBetUsers();
        Assert.assertNotNull("Find all method for 'BetUser' illegally returned null", result);
        Assert.assertTrue("Find all method for 'BetUser' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BetUserIntegrationTest.testFindBetUserEntries() {
        Assert.assertNotNull("Data on demand for 'BetUser' failed to initialize correctly", dod.getRandomBetUser());
        long count = BetUser.countBetUsers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<BetUser> result = BetUser.findBetUserEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'BetUser' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'BetUser' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BetUserIntegrationTest.testFlush() {
        BetUser obj = dod.getRandomBetUser();
        Assert.assertNotNull("Data on demand for 'BetUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BetUser' failed to provide an identifier", id);
        obj = BetUser.findBetUser(id);
        Assert.assertNotNull("Find method for 'BetUser' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBetUser(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'BetUser' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BetUserIntegrationTest.testMergeUpdate() {
        BetUser obj = dod.getRandomBetUser();
        Assert.assertNotNull("Data on demand for 'BetUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BetUser' failed to provide an identifier", id);
        obj = BetUser.findBetUser(id);
        boolean modified =  dod.modifyBetUser(obj);
        Integer currentVersion = obj.getVersion();
        BetUser merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'BetUser' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BetUserIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'BetUser' failed to initialize correctly", dod.getRandomBetUser());
        BetUser obj = dod.getNewTransientBetUser(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'BetUser' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'BetUser' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'BetUser' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BetUserIntegrationTest.testRemove() {
        BetUser obj = dod.getRandomBetUser();
        Assert.assertNotNull("Data on demand for 'BetUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'BetUser' failed to provide an identifier", id);
        obj = BetUser.findBetUser(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'BetUser' with identifier '" + id + "'", BetUser.findBetUser(id));
    }
    
}
