// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.zomtec.em2012.domain;

import eu.zomtec.em2012.domain.GameGroup;
import eu.zomtec.em2012.domain.GameGroupDataOnDemand;
import eu.zomtec.em2012.domain.GameGroupIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect GameGroupIntegrationTest_Roo_IntegrationTest {
    
    declare @type: GameGroupIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: GameGroupIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: GameGroupIntegrationTest: @Transactional;
    
    @Autowired
    private GameGroupDataOnDemand GameGroupIntegrationTest.dod;
    
    @Test
    public void GameGroupIntegrationTest.testCountGameGroups() {
        Assert.assertNotNull("Data on demand for 'GameGroup' failed to initialize correctly", dod.getRandomGameGroup());
        long count = GameGroup.countGameGroups();
        Assert.assertTrue("Counter for 'GameGroup' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void GameGroupIntegrationTest.testFindGameGroup() {
        GameGroup obj = dod.getRandomGameGroup();
        Assert.assertNotNull("Data on demand for 'GameGroup' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GameGroup' failed to provide an identifier", id);
        obj = GameGroup.findGameGroup(id);
        Assert.assertNotNull("Find method for 'GameGroup' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'GameGroup' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void GameGroupIntegrationTest.testFindAllGameGroups() {
        Assert.assertNotNull("Data on demand for 'GameGroup' failed to initialize correctly", dod.getRandomGameGroup());
        long count = GameGroup.countGameGroups();
        Assert.assertTrue("Too expensive to perform a find all test for 'GameGroup', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<GameGroup> result = GameGroup.findAllGameGroups();
        Assert.assertNotNull("Find all method for 'GameGroup' illegally returned null", result);
        Assert.assertTrue("Find all method for 'GameGroup' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void GameGroupIntegrationTest.testFindGameGroupEntries() {
        Assert.assertNotNull("Data on demand for 'GameGroup' failed to initialize correctly", dod.getRandomGameGroup());
        long count = GameGroup.countGameGroups();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<GameGroup> result = GameGroup.findGameGroupEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'GameGroup' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'GameGroup' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void GameGroupIntegrationTest.testFlush() {
        GameGroup obj = dod.getRandomGameGroup();
        Assert.assertNotNull("Data on demand for 'GameGroup' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GameGroup' failed to provide an identifier", id);
        obj = GameGroup.findGameGroup(id);
        Assert.assertNotNull("Find method for 'GameGroup' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyGameGroup(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'GameGroup' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GameGroupIntegrationTest.testMergeUpdate() {
        GameGroup obj = dod.getRandomGameGroup();
        Assert.assertNotNull("Data on demand for 'GameGroup' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GameGroup' failed to provide an identifier", id);
        obj = GameGroup.findGameGroup(id);
        boolean modified =  dod.modifyGameGroup(obj);
        Integer currentVersion = obj.getVersion();
        GameGroup merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'GameGroup' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GameGroupIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'GameGroup' failed to initialize correctly", dod.getRandomGameGroup());
        GameGroup obj = dod.getNewTransientGameGroup(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'GameGroup' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'GameGroup' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'GameGroup' identifier to no longer be null", obj.getId());
    }
}
