// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.zomtec.em2012.domain;

import eu.zomtec.em2012.domain.GameGroupDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect GameGroupDataOnDemand_Roo_Configurable {
    
    declare @type: GameGroupDataOnDemand: @Configurable;
    
}
