// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.zomtec.em2012.domain;

import eu.zomtec.em2012.domain.TeamGroup;
import eu.zomtec.em2012.domain.TeamGroupDataOnDemand;
import eu.zomtec.em2012.domain.TeamGroupIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TeamGroupIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TeamGroupIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TeamGroupIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TeamGroupIntegrationTest: @Transactional;
    
    @Autowired
    private TeamGroupDataOnDemand TeamGroupIntegrationTest.dod;
    
    @Test
    public void TeamGroupIntegrationTest.testCountTeamGroups() {
        Assert.assertNotNull("Data on demand for 'TeamGroup' failed to initialize correctly", dod.getRandomTeamGroup());
        long count = TeamGroup.countTeamGroups();
        Assert.assertTrue("Counter for 'TeamGroup' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TeamGroupIntegrationTest.testFindTeamGroup() {
        TeamGroup obj = dod.getRandomTeamGroup();
        Assert.assertNotNull("Data on demand for 'TeamGroup' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TeamGroup' failed to provide an identifier", id);
        obj = TeamGroup.findTeamGroup(id);
        Assert.assertNotNull("Find method for 'TeamGroup' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TeamGroup' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TeamGroupIntegrationTest.testFindAllTeamGroups() {
        Assert.assertNotNull("Data on demand for 'TeamGroup' failed to initialize correctly", dod.getRandomTeamGroup());
        long count = TeamGroup.countTeamGroups();
        Assert.assertTrue("Too expensive to perform a find all test for 'TeamGroup', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TeamGroup> result = TeamGroup.findAllTeamGroups();
        Assert.assertNotNull("Find all method for 'TeamGroup' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TeamGroup' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TeamGroupIntegrationTest.testFindTeamGroupEntries() {
        Assert.assertNotNull("Data on demand for 'TeamGroup' failed to initialize correctly", dod.getRandomTeamGroup());
        long count = TeamGroup.countTeamGroups();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TeamGroup> result = TeamGroup.findTeamGroupEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TeamGroup' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TeamGroup' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TeamGroupIntegrationTest.testFlush() {
        TeamGroup obj = dod.getRandomTeamGroup();
        Assert.assertNotNull("Data on demand for 'TeamGroup' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TeamGroup' failed to provide an identifier", id);
        obj = TeamGroup.findTeamGroup(id);
        Assert.assertNotNull("Find method for 'TeamGroup' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTeamGroup(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'TeamGroup' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TeamGroupIntegrationTest.testMergeUpdate() {
        TeamGroup obj = dod.getRandomTeamGroup();
        Assert.assertNotNull("Data on demand for 'TeamGroup' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TeamGroup' failed to provide an identifier", id);
        obj = TeamGroup.findTeamGroup(id);
        boolean modified =  dod.modifyTeamGroup(obj);
        Integer currentVersion = obj.getVersion();
        TeamGroup merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'TeamGroup' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TeamGroupIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'TeamGroup' failed to initialize correctly", dod.getRandomTeamGroup());
        TeamGroup obj = dod.getNewTransientTeamGroup(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TeamGroup' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TeamGroup' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'TeamGroup' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TeamGroupIntegrationTest.testRemove() {
        TeamGroup obj = dod.getRandomTeamGroup();
        Assert.assertNotNull("Data on demand for 'TeamGroup' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TeamGroup' failed to provide an identifier", id);
        obj = TeamGroup.findTeamGroup(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'TeamGroup' with identifier '" + id + "'", TeamGroup.findTeamGroup(id));
    }
    
}
