// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.zomtec.em2012.domain;

import eu.zomtec.em2012.domain.BetUserRole;

privileged aspect BetUserRole_Roo_JavaBean {
    
    public String BetUserRole.getName() {
        return this.name;
    }
    
    public void BetUserRole.setName(String name) {
        this.name = name;
    }
    
}
