// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.zomtec.em2012.domain;

import eu.zomtec.em2012.domain.TeamGroup;

privileged aspect TeamGroup_Roo_JavaBean {
    
    public String TeamGroup.getName() {
        return this.name;
    }
    
    public void TeamGroup.setName(String name) {
        this.name = name;
    }
    
}
